newsNow:
  baseUrl: ""
  sources:
    china:
      - ifeng
      - thepaper
      - tencent
      - zaobao
    social:
      - baidu
      - weibo
      - zhihu
      - douyin
      - tieba
      - hupu
      - bilibili
    tech:
      - coolapk
      - ithome
      - solidot
      - hackernews
    world:
      - sputniknewscn
      - cankaoxiaoxi
    finance:
      - wallstreetcn-hot
      - cls-hot
      - jin10

database:
  path: "./data/trend.db"

analysis:
  fetchInterval: 3600 # 每小时抓取一次数据
  historyHours: 24 # 分析最近24小时的数据
  push:
    pushTime:
      - "09:20"
      - "18:20"
    pushCount: 5 # 每次推送5个事件
  event: # 事件分析相关配置
    sourceCount: 3 # 信源阈值，至少需要3个不同的信源报道同一事件
    rankThreshold: 3 # 排名阈值，3个信源报道同一事件时，所有信源中该事件排名的平均值必须小于等于3
    trendThreshold: 6 # 趋势阈值，事件在最近6小时内热度分整体上升
    staleHours: 24 # 陈旧事件阈值，超过24小时（1天）未被新的信源报道的事件将被认为是陈旧事件
  repeatPush: # 重复推送相关配置
    sourceAddThreshold: 2 # 信源增加阈值，事件被至少2个新的信源报道时二次推送
    rankImproveThreshold: 3 # 排名提升阈值，事件排名提升至少3位时二次推送

llm:
  baseUrl: "" # 兼容OpenAI API的URL，程序会自动拼接`/v1/chat/completions`
  apiKey: "sk-xxx"
  model: "deepseek-chat"
  maxTokens: 4096

pushers:
  - type: unipush
    url: ""
    secret: "push-key"
    channels: "misc"
